///////////////////////////////////////////////////////////////////////
// IFC Extension for PGSuper
// Copyright © 1999-2026  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as
// published by the Washington State Department of Transportation,
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source
// License along with this program; if not, write to the Washington
// State Department of Transportation, Bridge and Structures Office,
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////
#pragma once

#include <EAF\EAFCommandLineInfo.h>

/*****************************************************************************
CLASS
   CIfcCommandLineInfo

   Command line parser for batch IFC import and export.

   Import an IFC model into a new PGSuper project:
   BridgeLink.exe /IfcImport=<model.ifc> <template.pgt> [/IfcOut=<project.pgs>] [/IfcLog=<import.log>] [/IfcMapping=<table.json>]

   The template file is opened by the application as a new project. The IFC model
   is then imported into that project and the project is saved.
   /IfcOut defaults to the IFC file name with a .pgs extension.
   /IfcLog defaults to the output file name with a .log extension.
   /IfcMapping defaults to the standard mapping table installed with the extension.

   Export a PGSuper project to an IFC model:
   BridgeLink.exe /IfcExport=<model.ifc> <project.pgs> [/IfcPropertyUnits=Display|System] [/IfcLog=<export.log>] [/IfcMapping=<table.json>] [/IfcIds=<design.ids>]

   The project is exported with the default export options.
   /IfcPropertyUnits=Display (default) exports property values in display units with their units,
   /IfcPropertyUnits=System exports property values in system units using the project units.
   /IfcLog defaults to the IFC file name with a .export.log extension.
   /IfcMapping defaults to the standard mapping table installed with the extension.
   /IfcIds also writes the design-value IDS for the exported model, with the default IDS options
   (girders pinned by Name).

   Write a mapping table as a general IDS (devdocs/MappingTablesDesign.md, M5):
   BridgeLink.exe /IfcTableToIds=<table.ids> <template.pgt> [/IfcMapping=<table.json>] [/IfcLog=<file.log>]

   Generate a mapping table from a general IDS, e.g. an agency IDS:
   BridgeLink.exe /IfcIdsToTable=<agency.ids> <template.pgt> /IfcTable=<table.json> [/IfcBinding=<binding.json>] [/IfcTableExtends=standard|none] [/IfcLog=<file.log>]

   The generated table extends the standard table with only what differs from it (/IfcTableExtends=standard, the default),
   or stands alone with everything the IDS has (/IfcTableExtends=none).
   Rewrite a mapping table in the style of the standard table (as the mapping table editor writes it):
   BridgeLink.exe /IfcFormatTable=<table.json> <template.pgt> /IfcTable=<formatted.json> [/IfcLog=<file.log>]

   The template only starts the application. /IfcLog defaults to the output file name with a .log extension.
   It has the notes (what the IDS can't express) or the report (facets without an element role or target).

   Put /IfcImport, /IfcExport, /IfcTableToIds, /IfcIdsToTable, or /IfcFormatTable first. PGSuper builds before the Test and TxDOT agent command line
   fix claim (and reject) any command line whose first parameter is not a flag.
*****************************************************************************/

class CIfcCommandLineInfo : public CEAFCommandLineInfo
{
public:
   CIfcCommandLineInfo();
   virtual ~CIfcCommandLineInfo();

   virtual void ParseParam(LPCTSTR lpszParam, BOOL bFlag, BOOL bLast) override;

   virtual CString GetUsageMessage() override;
   virtual CString GetErrorMessage() override;

   bool m_bIfcImport; // true if /IfcImport was given
   bool m_bIfcExport; // true if /IfcExport was given
   bool m_bTableToIds; // true if /IfcTableToIds was given
   bool m_bIdsToTable; // true if /IfcIdsToTable was given
   bool m_bFormatTable; // true if /IfcFormatTable was given
   CString m_strFormatTableFile; // mapping table read by /IfcFormatTable
   CString m_strToolIdsFile; // IDS written by /IfcTableToIds or read by /IfcIdsToTable
   CString m_strTableFile; // mapping table written by /IfcIdsToTable or /IfcFormatTable
   CString m_strBindingFile; // binding file for /IfcIdsToTable
   bool m_bTableExtendsStandard; // /IfcTableExtends: the table generated by /IfcIdsToTable extends the standard table
   CString m_strIfcFile; // IFC file to import or export
   CString m_strOutFile; // PGSuper project file created by an import
   CString m_strLogFile;
   CString m_strMappingFile; // import and export option, see CIfcImportOptions::mapping_file and CIfcExportOptions::mapping_file
   CString m_strIdsFile; // export option: also write the design-value IDS (see CIdsExporter)
   bool m_bDisplayUnitsForProperties; // export option, see CIfcExportOptions::display_units_for_properties

private:
   // Prevent accidental copying and assignment
   CIfcCommandLineInfo(const CIfcCommandLineInfo&) = delete;
   CIfcCommandLineInfo& operator=(const CIfcCommandLineInfo&) = delete;
};
