//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IfcExtensions.rc
//
#define IDR_PLUGINEXAMPLE               102
#define IDR_PGSUPERPROJECTIMPORTER      103
#define IDR_PGSPLICEPROJECTIMPORTER     106
#define IDC_4X3_ADD1                    202
#define IDC_4X3_ADD2                    203
#define IDB_BSI                         205
#define IDD_EXPORT_OPTIONS              206
#define IDD_DIALOG1                     208
#define IDD_IMPORT_OPTIONS              208
#define IDC_REPRESENTATION_CURVE        209
#define IDC_RADIO2                      210
#define IDC_REPRESENTATION_FOOTPRINT    210
#define IDI_ICON1                       210
#define IDI_BSI                         210
#define IDC_SWEEP_POLYLINE              211
#define IDD_IMPORT_RESULTS              211
#define IDC_RADIO3                      212
#define IDC_SWEEP_INDEXPOLYCURVE        212
#define IDC_ALIGNMENT_ONLY              213
#define IDC_ALIGNMENT_AND_BRIDGE        214
#define IDC_INCLUDE_CAMBER              215
#define IDC_INCLUDE_CAMBER_NO           216
#define IDC_BSDD                        218
#define IDC_WALL                        219
#define IDC_RAILING                     220
#define IDC_QUANTITIES                  221
#define IDC_WORK_PLAN                   222
#define IDC_CHECK1                      223
#define IDC_INCLUDE_REBAR               223
#define IDC_WORKPLAN                    224
#define IDC_POLYLINE                    225
#define IDC_GRADIENTCURVE               226
#define IDC_RADIO4                      227
#define IDC_TASK                        227
#define IDC_LOCAL_PLACEMENT             227
#define IDC_RADIO1                      228
#define IDC_LINEAR_PLACEMENT            228
#define IDC_MODEL_SSH                   229
#define IDC_MODEL_PFS                   230
#define IDC_MODEL_BREP                  231
#define IDC_EDIT1                       231
#define IDC_EDIT                        231
#define IDC_CHECK2                      232
#define IDC_PER_ACI131                  232
#define IDC_PROPERTY_UNITS              233
#define IDC_GIRDER_ONLY                 234
#define IDC_SPAN                        235
#define IDC_COMBO2                      236
#define IDC_GIRDER                      236
#define IDC_POLYLINE_TANGENT            237
#define IDC_LINE_TANGENTS               238
#define IDD_GEOREFERENCING              239
#define IDC_EPSG_CODE                   240
#define IDC_DESCRIPTION                 241
#define IDC_GEODETIC_DATUM              242
#define IDC_VERTICAL_DATUM              243
#define IDC_MAP_PROJECTION              244
#define IDC_EASTINGS                    245
#define IDC_NORTHINGS                   246
#define IDC_ORTHOGONAL_HEIGHT           247
#define IDC_XAXIS_ABSCISSA              248
#define IDC_XAXIS_ORDINATE              249
#define IDC_SCALE                       250
#define IDC_CRS_GROUPBOX                251
#define IDC_MAP_CONVERSION_GROUPBOX     252
#define IDC_EASTINGS_LABEL              253
#define IDC_NORTHINGS_LABEL             254
#define IDC_ORTHOGONAL_HEIGHT_LABEL     255
#define IDC_XAXIS_ABSCISSA_LABEL        256
#define IDC_XAXIS_ORDINATE_LABEL        257
#define IDC_SCALE_LABEL                 258
#define IDC_BROWSE_EPSG_CODE            259
#define IDC_BROWSE_VERTICAL_DATUM       260
#define IDD_EPSG_PICKER                 261
#define IDC_EPSG_SEARCH                 262
#define IDC_EPSG_LIST                   263
#define IDC_EPSG_LEGEND                 264
#define IDD_IDS_EXPORT_OPTIONS          265
#define IDC_IDS_ID_NAME                 266
#define IDC_IDS_ID_GLOBALID             267
#define IDC_IDS_ENABLED                 268
#define IDC_IDS_INC_BEAM_PROPS          269
#define IDC_IDS_INC_QUANTITIES          270
#define IDC_IDS_INC_CONCRETE_MATERIAL   271
#define IDC_IDS_INC_STRANDS             272
#define IDC_IDS_INC_REBAR               273
#define IDC_REBAR_INDIVIDUAL            274
#define IDC_REBAR_MAPPED                275
#define IDC_SURVEY_POINTS_NONE          276
#define IDC_SURVEY_POINTS_INDIVIDUAL    277
#define IDC_SURVEY_POINTS_SET           278
#define IDD_MAPPING_TABLE               279
#define IDC_MAPPING_STANDARD            280
#define IDC_MAPPING_AGENCY              281
#define IDC_MAPPING_FILE                282
#define IDC_MAPPING_BROWSE              283
#define IDC_MAPPING_STATUS              284
#define IDR_MAPPING_EDITOR              285
#define IDD_MAPPING_TABLE_PANE          286
#define IDD_MAPPING_SELECTOR_PANE       287
#define IDD_MAPPING_TARGET_PANE         288
#define IDD_MAPPING_INFO_PANE           289
#define IDD_MAPPING_LOCATION            290
#define IDC_TABLE_NAME                  292
#define IDC_TABLE_EXTENDS               293
#define IDC_TABLE_EXTENDS_BROWSE        294
#define IDC_TABLE_COMMENT               295
#define IDC_TABLE_INFO                  296
#define IDC_SELECTOR_HEADER             297
#define IDC_SELECTOR_INHERITED          298
#define IDC_SELECTOR_DEFINED            299
#define IDC_SELECTOR_ENTITY             300
#define IDC_SELECTOR_PREDEFINED         301
#define IDC_SELECTOR_CLASSIFICATION     302
#define IDC_SELECTOR_ATTRIBUTES         303
#define IDC_SELECTOR_NOTE               304
#define IDC_TARGET_HEADER               305
#define IDC_LOCATIONS                   306
#define IDC_LOCATION_ADD                307
#define IDC_LOCATION_EDIT               308
#define IDC_LOCATION_REMOVE             309
#define IDC_LOCATION_UP                 310
#define IDC_LOCATION_DOWN               311
#define IDC_REPLACE_BASE                312
#define IDC_BASE_LOCATIONS              313
#define IDC_INFO_TEXT                   314
#define IDC_LOC_PROPERTY                315
#define IDC_LOC_ATTRIBUTE               316
#define IDC_LOC_TYPE_ATTRIBUTE          317
#define IDC_LOC_CLASSIFICATION          318
#define IDC_LOC_PSET                    319
#define IDC_LOC_NAME                    320
#define IDC_LOC_ON                      321
#define IDC_LOC_SYSTEM                  322
#define IDC_LOC_IDENTIFICATION          323
#define IDC_LOC_FIELD                   324
#define IDC_LOC_UNIT                    325
#define IDC_LOC_PARSE                   326
#define IDC_LOC_REGEX                   327
#define IDC_LOC_GROUP                   328
#define IDC_LOC_LIST_INDEX              329
#define IDC_LOC_VALUE_TYPES             330
#define IDC_LOC_MAP                     331
#define IDC_LOC_COMMENT                 332
#define IDD_MAPPING_SECTION_PANE        333
#define IDD_MAPPING_BASE_ITEM_PANE      334
#define IDD_MAPPING_SET_PANE            335
#define IDD_MAPPING_PROPERTY            336
#define IDD_MAPPING_SYSTEM_PANE         337
#define IDD_MAPPING_CLASSIFICATION_PANE 338
#define IDC_SECTION_TEXT                340
#define IDC_SECTION_ADD                 341
#define IDC_BASE_TEXT                   342
#define IDC_BASE_CHANGE                 343
#define IDC_BASE_LEAVE_OUT              344
#define IDC_SET_NAME                    345
#define IDC_SET_ROLES                   346
#define IDC_SET_ATTACH_LABEL            347
#define IDC_SET_ATTACH                  348
#define IDC_SET_METHOD                  349
#define IDC_SET_CONDITION               350
#define IDC_SET_URI                     351
#define IDC_SET_SHARED                  352
#define IDC_SET_COMMENT                 353
#define IDC_SET_PROPERTIES              354
#define IDC_PROP_ADD                    355
#define IDC_PROP_EDIT                   356
#define IDC_PROP_REMOVE                 357
#define IDC_PROP_UP                     358
#define IDC_PROP_DOWN                   359
#define IDC_SET_DELETE                  360
#define IDC_SET_NOTE                    361
#define IDC_PROP_NAME                   362
#define IDC_PROP_TYPE                   363
#define IDC_PROP_NONE                   364
#define IDC_PROP_BIND_TARGET            365
#define IDC_PROP_BIND_VALUE             366
#define IDC_PROP_TARGET                 367
#define IDC_PROP_VALUE                  368
#define IDC_PROP_IMPORT                 369
#define IDC_PROP_URI                    370
#define IDC_PROP_ENUM_NAME              371
#define IDC_PROP_ENUM_VALUES            372
#define IDC_PROP_COMMENT                373
#define IDC_SYS_NAME                    374
#define IDC_SYS_SOURCE                  375
#define IDC_SYS_EDITION                 376
#define IDC_SYS_DATE                    377
#define IDC_SYS_SPEC                    378
#define IDC_SYS_COMMENT                 379
#define IDC_SYS_DELETE                  380
#define IDC_CLS_ROLES                   381
#define IDC_CLS_CONDITION               382
#define IDC_CLS_SYSTEM                  383
#define IDC_CLS_IDENTIFICATION          384
#define IDC_CLS_NAME                    385
#define IDC_CLS_LOCATION                386
#define IDC_CLS_COMMENT                 387
#define IDC_CLS_NOTE                    388
#define IDC_CLS_DELETE                  389
#define IDC_SET_ITEMS_LABEL             390
#define ID_EDIT_GEOREFERENCING          32771
#define ID_OPTIONS_IFC_MAPPING_TABLE    32772
#define ID_MAPPING_VALIDATE             32773
#define ID_MAPPING_WRITE_IDS            32774
#define ID_MAPPING_FROM_IDS             32775
#define IDD_MAPPING_FROM_IDS            391
#define IDC_FROMIDS_IDS                 392
#define IDC_FROMIDS_IDS_BROWSE          393
#define IDC_FROMIDS_BINDING             394
#define IDC_FROMIDS_BINDING_BROWSE      395
#define IDC_FROMIDS_EXTEND              396

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        397
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         397
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
