// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef SCHEMA_IDS_BINDING_HXX
#define SCHEMA_IDS_BINDING_HXX

#ifndef XSD_CXX11
#define XSD_CXX11
#endif

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

#include <xsd/cxx/xml/dom/serialization-header.hxx>
#include <xsd/cxx/tree/serialization.hxx>
#include <xsd/cxx/tree/serialization/byte.hxx>
#include <xsd/cxx/tree/serialization/unsigned-byte.hxx>
#include <xsd/cxx/tree/serialization/short.hxx>
#include <xsd/cxx/tree/serialization/unsigned-short.hxx>
#include <xsd/cxx/tree/serialization/int.hxx>
#include <xsd/cxx/tree/serialization/unsigned-int.hxx>
#include <xsd/cxx/tree/serialization/long.hxx>
#include <xsd/cxx/tree/serialization/unsigned-long.hxx>
#include <xsd/cxx/tree/serialization/boolean.hxx>
#include <xsd/cxx/tree/serialization/float.hxx>
#include <xsd/cxx/tree/serialization/double.hxx>
#include <xsd/cxx/tree/serialization/decimal.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type< char, type > simple_type;
  typedef ::xsd::cxx::tree::type container;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef long long non_positive_integer;
  typedef unsigned long long non_negative_integer;
  typedef unsigned long long positive_integer;
  typedef long long negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< char, string > normalized_string;
  typedef ::xsd::cxx::tree::token< char, normalized_string > token;
  typedef ::xsd::cxx::tree::name< char, token > name;
  typedef ::xsd::cxx::tree::nmtoken< char, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, simple_type, nmtoken > nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, name > ncname;
  typedef ::xsd::cxx::tree::language< char, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, ncname > id;
  typedef ::xsd::cxx::tree::idref< char, ncname, type > idref;
  typedef ::xsd::cxx::tree::idrefs< char, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< char, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::time_zone time_zone;
  typedef ::xsd::cxx::tree::date< char, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< char, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< char, simple_type > duration;
  typedef ::xsd::cxx::tree::gday< char, simple_type > gday;
  typedef ::xsd::cxx::tree::gmonth< char, simple_type > gmonth;
  typedef ::xsd::cxx::tree::gmonth_day< char, simple_type > gmonth_day;
  typedef ::xsd::cxx::tree::gyear< char, simple_type > gyear;
  typedef ::xsd::cxx::tree::gyear_month< char, simple_type > gyear_month;
  typedef ::xsd::cxx::tree::time< char, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, ncname > entity;
  typedef ::xsd::cxx::tree::entities< char, simple_type, entity > entities;

  typedef ::xsd::cxx::tree::content_order content_order;
  // Namespace information and list stream. Used in
  // serialization functions.
  //
  typedef ::xsd::cxx::xml::dom::namespace_info< char > namespace_info;
  typedef ::xsd::cxx::xml::dom::namespace_infomap< char > namespace_infomap;
  typedef ::xsd::cxx::tree::list_stream< char > list_stream;
  typedef ::xsd::cxx::tree::as_double< double_ > as_double;
  typedef ::xsd::cxx::tree::as_decimal< decimal > as_decimal;
  typedef ::xsd::cxx::tree::facet facet;

  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< char > properties;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< char > error;
  typedef ::xsd::cxx::tree::diagnostics< char > diagnostics;

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > exception;
  typedef ::xsd::cxx::tree::bounds< char > bounds;
  typedef ::xsd::cxx::tree::duplicate_id< char > duplicate_id;
  typedef ::xsd::cxx::tree::parsing< char > parsing;
  typedef ::xsd::cxx::tree::expected_element< char > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< char > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< char > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > expected_text_content;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > no_prefix_mapping;
  typedef ::xsd::cxx::tree::serialization< char > serialization;

  // Error handler callback interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // DOM interaction.
  //
  namespace dom
  {
    // Automatic pointer for DOMDocument.
    //
    using ::xsd::cxx::xml::dom::unique_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    // DOM user data key for back pointers to tree nodes.
    //
    const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
namespace IDS
{
  class entityType;
  class idsValue;
  class classificationType;
  class partOfType;
  class applicabilityType;
  class propertyType;
  class attributeType;
  class materialType;
  class requirementsType;
  class specificationType;
  class specificationsType;
  class relations;
  class upperCaseName;
  class simpleCardinality;
  class conditionalCardinality;
  class ids;
  class entity;
  class partOf;
  class classification;
  class attribute;
  class property;
  class material;
  class requirements;
  class ifcVersion;
  class info;
  class ifcVersion_item;
  class author;
}


#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include <xsd/cxx/tree/containers-wildcard.hxx>

namespace IDS
{
  class entityType: public ::xml_schema::type
  {
    public:
    // name
    //
    typedef ::IDS::idsValue name_type;
    typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

    const name_type&
    name () const;

    name_type&
    name ();

    void
    name (const name_type& x);

    void
    name (::std::unique_ptr< name_type > p);

    // predefinedType
    //
    typedef ::IDS::idsValue predefinedType_type;
    typedef ::xsd::cxx::tree::optional< predefinedType_type > predefinedType_optional;
    typedef ::xsd::cxx::tree::traits< predefinedType_type, char > predefinedType_traits;

    const predefinedType_optional&
    predefinedType () const;

    predefinedType_optional&
    predefinedType ();

    void
    predefinedType (const predefinedType_type& x);

    void
    predefinedType (const predefinedType_optional& x);

    void
    predefinedType (::std::unique_ptr< predefinedType_type > p);

    // Constructors.
    //
    entityType (const name_type&);

    entityType (::std::unique_ptr< name_type >);

    entityType (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

    entityType (const entityType& x,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

    virtual entityType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    entityType&
    operator= (const entityType& x);

    virtual 
    ~entityType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< name_type > name_;
    predefinedType_optional predefinedType_;
  };

  class idsValue: public ::xml_schema::type
  {
    public:
    // simpleValue
    //
    typedef ::xml_schema::string simpleValue_type;
    typedef ::xsd::cxx::tree::optional< simpleValue_type > simpleValue_optional;
    typedef ::xsd::cxx::tree::traits< simpleValue_type, char > simpleValue_traits;

    const simpleValue_optional&
    simpleValue () const;

    simpleValue_optional&
    simpleValue ();

    void
    simpleValue (const simpleValue_type& x);

    void
    simpleValue (const simpleValue_optional& x);

    void
    simpleValue (::std::unique_ptr< simpleValue_type > p);

    // any
    //
    typedef ::xsd::cxx::tree::element_optional any_optional;

    const any_optional&
    any () const;

    any_optional&
    any ();

    void
    any (const ::xercesc::DOMElement& e);

    void
    any (::xercesc::DOMElement* p);

    void
    any (const any_optional& x);

    // DOMDocument for wildcard content.
    //
    const ::xercesc::DOMDocument&
    dom_document () const;

    ::xercesc::DOMDocument&
    dom_document ();

    // Constructors.
    //
    idsValue ();

    idsValue (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

    idsValue (const idsValue& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

    virtual idsValue*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    idsValue&
    operator= (const idsValue& x);

    virtual 
    ~idsValue ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > dom_document_;

    simpleValue_optional simpleValue_;
    any_optional any_;
  };

  class classificationType: public ::xml_schema::type
  {
    public:
    // value
    //
    typedef ::IDS::idsValue value_type;
    typedef ::xsd::cxx::tree::optional< value_type > value_optional;
    typedef ::xsd::cxx::tree::traits< value_type, char > value_traits;

    const value_optional&
    value () const;

    value_optional&
    value ();

    void
    value (const value_type& x);

    void
    value (const value_optional& x);

    void
    value (::std::unique_ptr< value_type > p);

    // system
    //
    typedef ::IDS::idsValue system_type;
    typedef ::xsd::cxx::tree::traits< system_type, char > system_traits;

    const system_type&
    system () const;

    system_type&
    system ();

    void
    system (const system_type& x);

    void
    system (::std::unique_ptr< system_type > p);

    // Constructors.
    //
    classificationType (const system_type&);

    classificationType (::std::unique_ptr< system_type >);

    classificationType (const ::xercesc::DOMElement& e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

    classificationType (const classificationType& x,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

    virtual classificationType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    classificationType&
    operator= (const classificationType& x);

    virtual 
    ~classificationType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    value_optional value_;
    ::xsd::cxx::tree::one< system_type > system_;
  };

  class partOfType: public ::xml_schema::type
  {
    public:
    // entity
    //
    typedef ::IDS::entityType entity_type;
    typedef ::xsd::cxx::tree::traits< entity_type, char > entity_traits;

    const entity_type&
    entity () const;

    entity_type&
    entity ();

    void
    entity (const entity_type& x);

    void
    entity (::std::unique_ptr< entity_type > p);

    // relation
    //
    typedef ::IDS::relations relation_type;
    typedef ::xsd::cxx::tree::optional< relation_type > relation_optional;
    typedef ::xsd::cxx::tree::traits< relation_type, char > relation_traits;

    const relation_optional&
    relation () const;

    relation_optional&
    relation ();

    void
    relation (const relation_type& x);

    void
    relation (const relation_optional& x);

    void
    relation (::std::unique_ptr< relation_type > p);

    // Constructors.
    //
    partOfType (const entity_type&);

    partOfType (::std::unique_ptr< entity_type >);

    partOfType (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

    partOfType (const partOfType& x,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

    virtual partOfType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    partOfType&
    operator= (const partOfType& x);

    virtual 
    ~partOfType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< entity_type > entity_;
    relation_optional relation_;
  };

  class applicabilityType: public ::xml_schema::type
  {
    public:
    // entity
    //
    typedef ::IDS::entityType entity_type;
    typedef ::xsd::cxx::tree::optional< entity_type > entity_optional;
    typedef ::xsd::cxx::tree::traits< entity_type, char > entity_traits;

    const entity_optional&
    entity () const;

    entity_optional&
    entity ();

    void
    entity (const entity_type& x);

    void
    entity (const entity_optional& x);

    void
    entity (::std::unique_ptr< entity_type > p);

    // partOf
    //
    typedef ::IDS::partOfType partOf_type;
    typedef ::xsd::cxx::tree::sequence< partOf_type > partOf_sequence;
    typedef partOf_sequence::iterator partOf_iterator;
    typedef partOf_sequence::const_iterator partOf_const_iterator;
    typedef ::xsd::cxx::tree::traits< partOf_type, char > partOf_traits;

    const partOf_sequence&
    partOf () const;

    partOf_sequence&
    partOf ();

    void
    partOf (const partOf_sequence& s);

    // classification
    //
    typedef ::IDS::classificationType classification_type;
    typedef ::xsd::cxx::tree::sequence< classification_type > classification_sequence;
    typedef classification_sequence::iterator classification_iterator;
    typedef classification_sequence::const_iterator classification_const_iterator;
    typedef ::xsd::cxx::tree::traits< classification_type, char > classification_traits;

    const classification_sequence&
    classification () const;

    classification_sequence&
    classification ();

    void
    classification (const classification_sequence& s);

    // attribute
    //
    typedef ::IDS::attributeType attribute_type;
    typedef ::xsd::cxx::tree::sequence< attribute_type > attribute_sequence;
    typedef attribute_sequence::iterator attribute_iterator;
    typedef attribute_sequence::const_iterator attribute_const_iterator;
    typedef ::xsd::cxx::tree::traits< attribute_type, char > attribute_traits;

    const attribute_sequence&
    attribute () const;

    attribute_sequence&
    attribute ();

    void
    attribute (const attribute_sequence& s);

    // property
    //
    typedef ::IDS::propertyType property_type;
    typedef ::xsd::cxx::tree::sequence< property_type > property_sequence;
    typedef property_sequence::iterator property_iterator;
    typedef property_sequence::const_iterator property_const_iterator;
    typedef ::xsd::cxx::tree::traits< property_type, char > property_traits;

    const property_sequence&
    property () const;

    property_sequence&
    property ();

    void
    property (const property_sequence& s);

    // material
    //
    typedef ::IDS::materialType material_type;
    typedef ::xsd::cxx::tree::sequence< material_type > material_sequence;
    typedef material_sequence::iterator material_iterator;
    typedef material_sequence::const_iterator material_const_iterator;
    typedef ::xsd::cxx::tree::traits< material_type, char > material_traits;

    const material_sequence&
    material () const;

    material_sequence&
    material ();

    void
    material (const material_sequence& s);

    // minOccurs
    //
    typedef ::xml_schema::string minOccurs_type;
    typedef ::xsd::cxx::tree::optional< minOccurs_type > minOccurs_optional;
    typedef ::xsd::cxx::tree::traits< minOccurs_type, char > minOccurs_traits;

    const minOccurs_optional&
    minOccurs () const;

    minOccurs_optional&
    minOccurs ();

    void
    minOccurs (const minOccurs_type& x);

    void
    minOccurs (const minOccurs_optional& x);

    void
    minOccurs (::std::unique_ptr< minOccurs_type > p);

    // maxOccurs
    //
    typedef ::xml_schema::string maxOccurs_type;
    typedef ::xsd::cxx::tree::optional< maxOccurs_type > maxOccurs_optional;
    typedef ::xsd::cxx::tree::traits< maxOccurs_type, char > maxOccurs_traits;

    const maxOccurs_optional&
    maxOccurs () const;

    maxOccurs_optional&
    maxOccurs ();

    void
    maxOccurs (const maxOccurs_type& x);

    void
    maxOccurs (const maxOccurs_optional& x);

    void
    maxOccurs (::std::unique_ptr< maxOccurs_type > p);

    // Constructors.
    //
    applicabilityType ();

    applicabilityType (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

    applicabilityType (const applicabilityType& x,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

    virtual applicabilityType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    applicabilityType&
    operator= (const applicabilityType& x);

    virtual 
    ~applicabilityType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    entity_optional entity_;
    partOf_sequence partOf_;
    classification_sequence classification_;
    attribute_sequence attribute_;
    property_sequence property_;
    material_sequence material_;
    minOccurs_optional minOccurs_;
    maxOccurs_optional maxOccurs_;
  };

  class propertyType: public ::xml_schema::type
  {
    public:
    // propertySet
    //
    typedef ::IDS::idsValue propertySet_type;
    typedef ::xsd::cxx::tree::traits< propertySet_type, char > propertySet_traits;

    const propertySet_type&
    propertySet () const;

    propertySet_type&
    propertySet ();

    void
    propertySet (const propertySet_type& x);

    void
    propertySet (::std::unique_ptr< propertySet_type > p);

    // baseName
    //
    typedef ::IDS::idsValue baseName_type;
    typedef ::xsd::cxx::tree::traits< baseName_type, char > baseName_traits;

    const baseName_type&
    baseName () const;

    baseName_type&
    baseName ();

    void
    baseName (const baseName_type& x);

    void
    baseName (::std::unique_ptr< baseName_type > p);

    // value
    //
    typedef ::IDS::idsValue value_type;
    typedef ::xsd::cxx::tree::optional< value_type > value_optional;
    typedef ::xsd::cxx::tree::traits< value_type, char > value_traits;

    const value_optional&
    value () const;

    value_optional&
    value ();

    void
    value (const value_type& x);

    void
    value (const value_optional& x);

    void
    value (::std::unique_ptr< value_type > p);

    // dataType
    //
    typedef ::IDS::upperCaseName dataType_type;
    typedef ::xsd::cxx::tree::optional< dataType_type > dataType_optional;
    typedef ::xsd::cxx::tree::traits< dataType_type, char > dataType_traits;

    const dataType_optional&
    dataType () const;

    dataType_optional&
    dataType ();

    void
    dataType (const dataType_type& x);

    void
    dataType (const dataType_optional& x);

    void
    dataType (::std::unique_ptr< dataType_type > p);

    // Constructors.
    //
    propertyType (const propertySet_type&,
                  const baseName_type&);

    propertyType (::std::unique_ptr< propertySet_type >,
                  ::std::unique_ptr< baseName_type >);

    propertyType (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

    propertyType (const propertyType& x,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

    virtual propertyType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    propertyType&
    operator= (const propertyType& x);

    virtual 
    ~propertyType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< propertySet_type > propertySet_;
    ::xsd::cxx::tree::one< baseName_type > baseName_;
    value_optional value_;
    dataType_optional dataType_;
  };

  class attributeType: public ::xml_schema::type
  {
    public:
    // name
    //
    typedef ::IDS::idsValue name_type;
    typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

    const name_type&
    name () const;

    name_type&
    name ();

    void
    name (const name_type& x);

    void
    name (::std::unique_ptr< name_type > p);

    // value
    //
    typedef ::IDS::idsValue value_type;
    typedef ::xsd::cxx::tree::optional< value_type > value_optional;
    typedef ::xsd::cxx::tree::traits< value_type, char > value_traits;

    const value_optional&
    value () const;

    value_optional&
    value ();

    void
    value (const value_type& x);

    void
    value (const value_optional& x);

    void
    value (::std::unique_ptr< value_type > p);

    // Constructors.
    //
    attributeType (const name_type&);

    attributeType (::std::unique_ptr< name_type >);

    attributeType (const ::xercesc::DOMElement& e,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

    attributeType (const attributeType& x,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

    virtual attributeType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    attributeType&
    operator= (const attributeType& x);

    virtual 
    ~attributeType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< name_type > name_;
    value_optional value_;
  };

  class materialType: public ::xml_schema::type
  {
    public:
    // value
    //
    typedef ::IDS::idsValue value_type;
    typedef ::xsd::cxx::tree::optional< value_type > value_optional;
    typedef ::xsd::cxx::tree::traits< value_type, char > value_traits;

    const value_optional&
    value () const;

    value_optional&
    value ();

    void
    value (const value_type& x);

    void
    value (const value_optional& x);

    void
    value (::std::unique_ptr< value_type > p);

    // Constructors.
    //
    materialType ();

    materialType (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

    materialType (const materialType& x,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

    virtual materialType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    materialType&
    operator= (const materialType& x);

    virtual 
    ~materialType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    value_optional value_;
  };

  class requirementsType: public ::xml_schema::type
  {
    public:
    // entity
    //
    typedef ::IDS::entity entity_type;
    typedef ::xsd::cxx::tree::sequence< entity_type > entity_sequence;
    typedef entity_sequence::iterator entity_iterator;
    typedef entity_sequence::const_iterator entity_const_iterator;
    typedef ::xsd::cxx::tree::traits< entity_type, char > entity_traits;

    const entity_sequence&
    entity () const;

    entity_sequence&
    entity ();

    void
    entity (const entity_sequence& s);

    // partOf
    //
    typedef ::IDS::partOf partOf_type;
    typedef ::xsd::cxx::tree::sequence< partOf_type > partOf_sequence;
    typedef partOf_sequence::iterator partOf_iterator;
    typedef partOf_sequence::const_iterator partOf_const_iterator;
    typedef ::xsd::cxx::tree::traits< partOf_type, char > partOf_traits;

    const partOf_sequence&
    partOf () const;

    partOf_sequence&
    partOf ();

    void
    partOf (const partOf_sequence& s);

    // classification
    //
    typedef ::IDS::classification classification_type;
    typedef ::xsd::cxx::tree::sequence< classification_type > classification_sequence;
    typedef classification_sequence::iterator classification_iterator;
    typedef classification_sequence::const_iterator classification_const_iterator;
    typedef ::xsd::cxx::tree::traits< classification_type, char > classification_traits;

    const classification_sequence&
    classification () const;

    classification_sequence&
    classification ();

    void
    classification (const classification_sequence& s);

    // attribute
    //
    typedef ::IDS::attribute attribute_type;
    typedef ::xsd::cxx::tree::sequence< attribute_type > attribute_sequence;
    typedef attribute_sequence::iterator attribute_iterator;
    typedef attribute_sequence::const_iterator attribute_const_iterator;
    typedef ::xsd::cxx::tree::traits< attribute_type, char > attribute_traits;

    const attribute_sequence&
    attribute () const;

    attribute_sequence&
    attribute ();

    void
    attribute (const attribute_sequence& s);

    // property
    //
    typedef ::IDS::property property_type;
    typedef ::xsd::cxx::tree::sequence< property_type > property_sequence;
    typedef property_sequence::iterator property_iterator;
    typedef property_sequence::const_iterator property_const_iterator;
    typedef ::xsd::cxx::tree::traits< property_type, char > property_traits;

    const property_sequence&
    property () const;

    property_sequence&
    property ();

    void
    property (const property_sequence& s);

    // material
    //
    typedef ::IDS::material material_type;
    typedef ::xsd::cxx::tree::sequence< material_type > material_sequence;
    typedef material_sequence::iterator material_iterator;
    typedef material_sequence::const_iterator material_const_iterator;
    typedef ::xsd::cxx::tree::traits< material_type, char > material_traits;

    const material_sequence&
    material () const;

    material_sequence&
    material ();

    void
    material (const material_sequence& s);

    // Constructors.
    //
    requirementsType ();

    requirementsType (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

    requirementsType (const requirementsType& x,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

    virtual requirementsType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    requirementsType&
    operator= (const requirementsType& x);

    virtual 
    ~requirementsType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    entity_sequence entity_;
    partOf_sequence partOf_;
    classification_sequence classification_;
    attribute_sequence attribute_;
    property_sequence property_;
    material_sequence material_;
  };

  class specificationType: public ::xml_schema::type
  {
    public:
    // applicability
    //
    typedef ::IDS::applicabilityType applicability_type;
    typedef ::xsd::cxx::tree::traits< applicability_type, char > applicability_traits;

    const applicability_type&
    applicability () const;

    applicability_type&
    applicability ();

    void
    applicability (const applicability_type& x);

    void
    applicability (::std::unique_ptr< applicability_type > p);

    // requirements
    //
    typedef ::IDS::requirements requirements_type;
    typedef ::xsd::cxx::tree::optional< requirements_type > requirements_optional;
    typedef ::xsd::cxx::tree::traits< requirements_type, char > requirements_traits;

    const requirements_optional&
    requirements () const;

    requirements_optional&
    requirements ();

    void
    requirements (const requirements_type& x);

    void
    requirements (const requirements_optional& x);

    void
    requirements (::std::unique_ptr< requirements_type > p);

    // name
    //
    typedef ::xml_schema::string name_type;
    typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

    const name_type&
    name () const;

    name_type&
    name ();

    void
    name (const name_type& x);

    void
    name (::std::unique_ptr< name_type > p);

    // ifcVersion
    //
    typedef ::IDS::ifcVersion ifcVersion_type;
    typedef ::xsd::cxx::tree::traits< ifcVersion_type, char > ifcVersion_traits;

    const ifcVersion_type&
    ifcVersion () const;

    ifcVersion_type&
    ifcVersion ();

    void
    ifcVersion (const ifcVersion_type& x);

    void
    ifcVersion (::std::unique_ptr< ifcVersion_type > p);

    // identifier
    //
    typedef ::xml_schema::string identifier_type;
    typedef ::xsd::cxx::tree::optional< identifier_type > identifier_optional;
    typedef ::xsd::cxx::tree::traits< identifier_type, char > identifier_traits;

    const identifier_optional&
    identifier () const;

    identifier_optional&
    identifier ();

    void
    identifier (const identifier_type& x);

    void
    identifier (const identifier_optional& x);

    void
    identifier (::std::unique_ptr< identifier_type > p);

    // description
    //
    typedef ::xml_schema::string description_type;
    typedef ::xsd::cxx::tree::optional< description_type > description_optional;
    typedef ::xsd::cxx::tree::traits< description_type, char > description_traits;

    const description_optional&
    description () const;

    description_optional&
    description ();

    void
    description (const description_type& x);

    void
    description (const description_optional& x);

    void
    description (::std::unique_ptr< description_type > p);

    // instructions
    //
    typedef ::xml_schema::string instructions_type;
    typedef ::xsd::cxx::tree::optional< instructions_type > instructions_optional;
    typedef ::xsd::cxx::tree::traits< instructions_type, char > instructions_traits;

    const instructions_optional&
    instructions () const;

    instructions_optional&
    instructions ();

    void
    instructions (const instructions_type& x);

    void
    instructions (const instructions_optional& x);

    void
    instructions (::std::unique_ptr< instructions_type > p);

    // Constructors.
    //
    specificationType (const applicability_type&,
                       const name_type&,
                       const ifcVersion_type&);

    specificationType (::std::unique_ptr< applicability_type >,
                       const name_type&,
                       const ifcVersion_type&);

    specificationType (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

    specificationType (const specificationType& x,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

    virtual specificationType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    specificationType&
    operator= (const specificationType& x);

    virtual 
    ~specificationType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< applicability_type > applicability_;
    requirements_optional requirements_;
    ::xsd::cxx::tree::one< name_type > name_;
    ::xsd::cxx::tree::one< ifcVersion_type > ifcVersion_;
    identifier_optional identifier_;
    description_optional description_;
    instructions_optional instructions_;
  };

  class specificationsType: public ::xml_schema::type
  {
    public:
    // specification
    //
    typedef ::IDS::specificationType specification_type;
    typedef ::xsd::cxx::tree::sequence< specification_type > specification_sequence;
    typedef specification_sequence::iterator specification_iterator;
    typedef specification_sequence::const_iterator specification_const_iterator;
    typedef ::xsd::cxx::tree::traits< specification_type, char > specification_traits;

    const specification_sequence&
    specification () const;

    specification_sequence&
    specification ();

    void
    specification (const specification_sequence& s);

    // Constructors.
    //
    specificationsType ();

    specificationsType (const ::xercesc::DOMElement& e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

    specificationsType (const specificationsType& x,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

    virtual specificationsType*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    specificationsType&
    operator= (const specificationsType& x);

    virtual 
    ~specificationsType ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    specification_sequence specification_;
  };

  class relations: public ::xml_schema::string
  {
    public:
    enum value
    {
      IFCRELAGGREGATES,
      IFCRELASSIGNSTOGROUP,
      IFCRELCONTAINEDINSPATIALSTRUCTURE,
      IFCRELNESTS,
      IFCRELVOIDSELEMENT_IFCRELFILLSELEMENT
    };

    relations (value v);

    relations (const char* v);

    relations (const ::std::string& v);

    relations (const ::xml_schema::string& v);

    relations (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

    relations (const ::xercesc::DOMAttr& a,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

    relations (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

    relations (const relations& x,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

#ifdef XSD_CXX11
    relations&
    operator= (const relations&) = default;
#endif

    virtual relations*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    relations&
    operator= (value v);

    virtual
    operator value () const
    {
      return _xsd_relations_convert ();
    }

    protected:
    value
    _xsd_relations_convert () const;

    public:
    static const char* const _xsd_relations_literals_[5];
    static const value _xsd_relations_indexes_[5];
  };

  class upperCaseName: public ::xml_schema::normalized_string
  {
    public:
    // Constructors.
    //
    upperCaseName ();

    upperCaseName (const char*);

    upperCaseName (const ::std::string&);

    upperCaseName (const ::xml_schema::normalized_string&);

    upperCaseName (const ::xercesc::DOMElement& e,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

    upperCaseName (const ::xercesc::DOMAttr& a,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

    upperCaseName (const ::std::string& s,
                   const ::xercesc::DOMElement* e,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

    upperCaseName (const upperCaseName& x,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

    virtual upperCaseName*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

#ifdef XSD_CXX11
    upperCaseName&
    operator= (const upperCaseName&) = default;
#endif

    virtual 
    ~upperCaseName ();
  };

  class simpleCardinality: public ::xml_schema::string
  {
    public:
    enum value
    {
      required,
      prohibited
    };

    simpleCardinality (value v);

    simpleCardinality (const char* v);

    simpleCardinality (const ::std::string& v);

    simpleCardinality (const ::xml_schema::string& v);

    simpleCardinality (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

    simpleCardinality (const ::xercesc::DOMAttr& a,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

    simpleCardinality (const ::std::string& s,
                       const ::xercesc::DOMElement* e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

    simpleCardinality (const simpleCardinality& x,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

#ifdef XSD_CXX11
    simpleCardinality&
    operator= (const simpleCardinality&) = default;
#endif

    virtual simpleCardinality*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    simpleCardinality&
    operator= (value v);

    virtual
    operator value () const
    {
      return _xsd_simpleCardinality_convert ();
    }

    protected:
    value
    _xsd_simpleCardinality_convert () const;

    public:
    static const char* const _xsd_simpleCardinality_literals_[2];
    static const value _xsd_simpleCardinality_indexes_[2];
  };

  class conditionalCardinality: public ::xml_schema::string
  {
    public:
    enum value
    {
      required,
      prohibited,
      optional
    };

    conditionalCardinality (value v);

    conditionalCardinality (const char* v);

    conditionalCardinality (const ::std::string& v);

    conditionalCardinality (const ::xml_schema::string& v);

    conditionalCardinality (const ::xercesc::DOMElement& e,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

    conditionalCardinality (const ::xercesc::DOMAttr& a,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

    conditionalCardinality (const ::std::string& s,
                            const ::xercesc::DOMElement* e,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

    conditionalCardinality (const conditionalCardinality& x,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

#ifdef XSD_CXX11
    conditionalCardinality&
    operator= (const conditionalCardinality&) = default;
#endif

    virtual conditionalCardinality*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    conditionalCardinality&
    operator= (value v);

    virtual
    operator value () const
    {
      return _xsd_conditionalCardinality_convert ();
    }

    protected:
    value
    _xsd_conditionalCardinality_convert () const;

    public:
    static const char* const _xsd_conditionalCardinality_literals_[3];
    static const value _xsd_conditionalCardinality_indexes_[3];
  };

  class ids: public ::xml_schema::type
  {
    public:
    // info
    //
    typedef ::IDS::info info_type;
    typedef ::xsd::cxx::tree::traits< info_type, char > info_traits;

    const info_type&
    info () const;

    info_type&
    info ();

    void
    info (const info_type& x);

    void
    info (::std::unique_ptr< info_type > p);

    // specifications
    //
    typedef ::IDS::specificationsType specifications_type;
    typedef ::xsd::cxx::tree::traits< specifications_type, char > specifications_traits;

    const specifications_type&
    specifications () const;

    specifications_type&
    specifications ();

    void
    specifications (const specifications_type& x);

    void
    specifications (::std::unique_ptr< specifications_type > p);

    // Constructors.
    //
    ids (const info_type&,
         const specifications_type&);

    ids (::std::unique_ptr< info_type >,
         ::std::unique_ptr< specifications_type >);

    ids (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f = 0,
         ::xml_schema::container* c = 0);

    ids (const ids& x,
         ::xml_schema::flags f = 0,
         ::xml_schema::container* c = 0);

    virtual ids*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    ids&
    operator= (const ids& x);

    virtual 
    ~ids ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< info_type > info_;
    ::xsd::cxx::tree::one< specifications_type > specifications_;
  };

  class entity: public ::IDS::entityType
  {
    public:
    // instructions
    //
    typedef ::xml_schema::string instructions_type;
    typedef ::xsd::cxx::tree::optional< instructions_type > instructions_optional;
    typedef ::xsd::cxx::tree::traits< instructions_type, char > instructions_traits;

    const instructions_optional&
    instructions () const;

    instructions_optional&
    instructions ();

    void
    instructions (const instructions_type& x);

    void
    instructions (const instructions_optional& x);

    void
    instructions (::std::unique_ptr< instructions_type > p);

    // Constructors.
    //
    entity (const name_type&);

    entity (::std::unique_ptr< name_type >);

    entity (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

    entity (const entity& x,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

    virtual entity*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    entity&
    operator= (const entity& x);

    virtual 
    ~entity ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    instructions_optional instructions_;
  };

  class partOf: public ::IDS::partOfType
  {
    public:
    // cardinality
    //
    typedef ::IDS::simpleCardinality cardinality_type;
    typedef ::xsd::cxx::tree::traits< cardinality_type, char > cardinality_traits;

    const cardinality_type&
    cardinality () const;

    cardinality_type&
    cardinality ();

    void
    cardinality (const cardinality_type& x);

    void
    cardinality (::std::unique_ptr< cardinality_type > p);

    static const cardinality_type&
    cardinality_default_value ();

    // instructions
    //
    typedef ::xml_schema::string instructions_type;
    typedef ::xsd::cxx::tree::optional< instructions_type > instructions_optional;
    typedef ::xsd::cxx::tree::traits< instructions_type, char > instructions_traits;

    const instructions_optional&
    instructions () const;

    instructions_optional&
    instructions ();

    void
    instructions (const instructions_type& x);

    void
    instructions (const instructions_optional& x);

    void
    instructions (::std::unique_ptr< instructions_type > p);

    // Constructors.
    //
    partOf (const entity_type&);

    partOf (::std::unique_ptr< entity_type >);

    partOf (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

    partOf (const partOf& x,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

    virtual partOf*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    partOf&
    operator= (const partOf& x);

    virtual 
    ~partOf ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< cardinality_type > cardinality_;
    static const cardinality_type cardinality_default_value_;
    instructions_optional instructions_;
  };

  class classification: public ::IDS::classificationType
  {
    public:
    // uri
    //
    typedef ::xml_schema::uri uri_type;
    typedef ::xsd::cxx::tree::optional< uri_type > uri_optional;
    typedef ::xsd::cxx::tree::traits< uri_type, char > uri_traits;

    const uri_optional&
    uri () const;

    uri_optional&
    uri ();

    void
    uri (const uri_type& x);

    void
    uri (const uri_optional& x);

    void
    uri (::std::unique_ptr< uri_type > p);

    // cardinality
    //
    typedef ::IDS::conditionalCardinality cardinality_type;
    typedef ::xsd::cxx::tree::traits< cardinality_type, char > cardinality_traits;

    const cardinality_type&
    cardinality () const;

    cardinality_type&
    cardinality ();

    void
    cardinality (const cardinality_type& x);

    void
    cardinality (::std::unique_ptr< cardinality_type > p);

    static const cardinality_type&
    cardinality_default_value ();

    // instructions
    //
    typedef ::xml_schema::string instructions_type;
    typedef ::xsd::cxx::tree::optional< instructions_type > instructions_optional;
    typedef ::xsd::cxx::tree::traits< instructions_type, char > instructions_traits;

    const instructions_optional&
    instructions () const;

    instructions_optional&
    instructions ();

    void
    instructions (const instructions_type& x);

    void
    instructions (const instructions_optional& x);

    void
    instructions (::std::unique_ptr< instructions_type > p);

    // Constructors.
    //
    classification (const system_type&);

    classification (::std::unique_ptr< system_type >);

    classification (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

    classification (const classification& x,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

    virtual classification*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    classification&
    operator= (const classification& x);

    virtual 
    ~classification ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    uri_optional uri_;
    ::xsd::cxx::tree::one< cardinality_type > cardinality_;
    static const cardinality_type cardinality_default_value_;
    instructions_optional instructions_;
  };

  class attribute: public ::IDS::attributeType
  {
    public:
    // cardinality
    //
    typedef ::IDS::conditionalCardinality cardinality_type;
    typedef ::xsd::cxx::tree::traits< cardinality_type, char > cardinality_traits;

    const cardinality_type&
    cardinality () const;

    cardinality_type&
    cardinality ();

    void
    cardinality (const cardinality_type& x);

    void
    cardinality (::std::unique_ptr< cardinality_type > p);

    static const cardinality_type&
    cardinality_default_value ();

    // instructions
    //
    typedef ::xml_schema::string instructions_type;
    typedef ::xsd::cxx::tree::optional< instructions_type > instructions_optional;
    typedef ::xsd::cxx::tree::traits< instructions_type, char > instructions_traits;

    const instructions_optional&
    instructions () const;

    instructions_optional&
    instructions ();

    void
    instructions (const instructions_type& x);

    void
    instructions (const instructions_optional& x);

    void
    instructions (::std::unique_ptr< instructions_type > p);

    // Constructors.
    //
    attribute (const name_type&);

    attribute (::std::unique_ptr< name_type >);

    attribute (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

    attribute (const attribute& x,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

    virtual attribute*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    attribute&
    operator= (const attribute& x);

    virtual 
    ~attribute ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< cardinality_type > cardinality_;
    static const cardinality_type cardinality_default_value_;
    instructions_optional instructions_;
  };

  class property: public ::IDS::propertyType
  {
    public:
    // uri
    //
    typedef ::xml_schema::uri uri_type;
    typedef ::xsd::cxx::tree::optional< uri_type > uri_optional;
    typedef ::xsd::cxx::tree::traits< uri_type, char > uri_traits;

    const uri_optional&
    uri () const;

    uri_optional&
    uri ();

    void
    uri (const uri_type& x);

    void
    uri (const uri_optional& x);

    void
    uri (::std::unique_ptr< uri_type > p);

    // cardinality
    //
    typedef ::IDS::conditionalCardinality cardinality_type;
    typedef ::xsd::cxx::tree::traits< cardinality_type, char > cardinality_traits;

    const cardinality_type&
    cardinality () const;

    cardinality_type&
    cardinality ();

    void
    cardinality (const cardinality_type& x);

    void
    cardinality (::std::unique_ptr< cardinality_type > p);

    static const cardinality_type&
    cardinality_default_value ();

    // instructions
    //
    typedef ::xml_schema::string instructions_type;
    typedef ::xsd::cxx::tree::optional< instructions_type > instructions_optional;
    typedef ::xsd::cxx::tree::traits< instructions_type, char > instructions_traits;

    const instructions_optional&
    instructions () const;

    instructions_optional&
    instructions ();

    void
    instructions (const instructions_type& x);

    void
    instructions (const instructions_optional& x);

    void
    instructions (::std::unique_ptr< instructions_type > p);

    // Constructors.
    //
    property (const propertySet_type&,
              const baseName_type&);

    property (::std::unique_ptr< propertySet_type >,
              ::std::unique_ptr< baseName_type >);

    property (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

    property (const property& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

    virtual property*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    property&
    operator= (const property& x);

    virtual 
    ~property ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    uri_optional uri_;
    ::xsd::cxx::tree::one< cardinality_type > cardinality_;
    static const cardinality_type cardinality_default_value_;
    instructions_optional instructions_;
  };

  class material: public ::IDS::materialType
  {
    public:
    // uri
    //
    typedef ::xml_schema::uri uri_type;
    typedef ::xsd::cxx::tree::optional< uri_type > uri_optional;
    typedef ::xsd::cxx::tree::traits< uri_type, char > uri_traits;

    const uri_optional&
    uri () const;

    uri_optional&
    uri ();

    void
    uri (const uri_type& x);

    void
    uri (const uri_optional& x);

    void
    uri (::std::unique_ptr< uri_type > p);

    // cardinality
    //
    typedef ::IDS::conditionalCardinality cardinality_type;
    typedef ::xsd::cxx::tree::traits< cardinality_type, char > cardinality_traits;

    const cardinality_type&
    cardinality () const;

    cardinality_type&
    cardinality ();

    void
    cardinality (const cardinality_type& x);

    void
    cardinality (::std::unique_ptr< cardinality_type > p);

    static const cardinality_type&
    cardinality_default_value ();

    // instructions
    //
    typedef ::xml_schema::string instructions_type;
    typedef ::xsd::cxx::tree::optional< instructions_type > instructions_optional;
    typedef ::xsd::cxx::tree::traits< instructions_type, char > instructions_traits;

    const instructions_optional&
    instructions () const;

    instructions_optional&
    instructions ();

    void
    instructions (const instructions_type& x);

    void
    instructions (const instructions_optional& x);

    void
    instructions (::std::unique_ptr< instructions_type > p);

    // Constructors.
    //
    material ();

    material (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

    material (const material& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

    virtual material*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    material&
    operator= (const material& x);

    virtual 
    ~material ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    uri_optional uri_;
    ::xsd::cxx::tree::one< cardinality_type > cardinality_;
    static const cardinality_type cardinality_default_value_;
    instructions_optional instructions_;
  };

  class requirements: public ::IDS::requirementsType
  {
    public:
    // description
    //
    typedef ::xml_schema::string description_type;
    typedef ::xsd::cxx::tree::optional< description_type > description_optional;
    typedef ::xsd::cxx::tree::traits< description_type, char > description_traits;

    const description_optional&
    description () const;

    description_optional&
    description ();

    void
    description (const description_type& x);

    void
    description (const description_optional& x);

    void
    description (::std::unique_ptr< description_type > p);

    // Constructors.
    //
    requirements ();

    requirements (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

    requirements (const requirements& x,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

    virtual requirements*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    requirements&
    operator= (const requirements& x);

    virtual 
    ~requirements ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    description_optional description_;
  };

  class ifcVersion: public ::xml_schema::simple_type,
    public ::xsd::cxx::tree::list< ::IDS::ifcVersion_item, char >
  {
    public:
    ifcVersion ();

    ifcVersion (size_type n, const ::IDS::ifcVersion_item& x);

    template < typename I >
    ifcVersion (const I& begin, const I& end)
    : ::xsd::cxx::tree::list< ::IDS::ifcVersion_item, char > (begin, end, this)
    {
    }

    ifcVersion (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

    ifcVersion (const ::xercesc::DOMAttr& a,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

    ifcVersion (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

    ifcVersion (const ifcVersion& x,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

#ifdef XSD_CXX11
    ifcVersion&
    operator= (const ifcVersion&) = default;
#endif

    virtual ifcVersion*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    virtual 
    ~ifcVersion ();
  };

  class info: public ::xml_schema::type
  {
    public:
    // title
    //
    typedef ::xml_schema::string title_type;
    typedef ::xsd::cxx::tree::traits< title_type, char > title_traits;

    const title_type&
    title () const;

    title_type&
    title ();

    void
    title (const title_type& x);

    void
    title (::std::unique_ptr< title_type > p);

    // copyright
    //
    typedef ::xml_schema::string copyright_type;
    typedef ::xsd::cxx::tree::optional< copyright_type > copyright_optional;
    typedef ::xsd::cxx::tree::traits< copyright_type, char > copyright_traits;

    const copyright_optional&
    copyright () const;

    copyright_optional&
    copyright ();

    void
    copyright (const copyright_type& x);

    void
    copyright (const copyright_optional& x);

    void
    copyright (::std::unique_ptr< copyright_type > p);

    // version
    //
    typedef ::xml_schema::string version_type;
    typedef ::xsd::cxx::tree::optional< version_type > version_optional;
    typedef ::xsd::cxx::tree::traits< version_type, char > version_traits;

    const version_optional&
    version () const;

    version_optional&
    version ();

    void
    version (const version_type& x);

    void
    version (const version_optional& x);

    void
    version (::std::unique_ptr< version_type > p);

    // description
    //
    typedef ::xml_schema::string description_type;
    typedef ::xsd::cxx::tree::optional< description_type > description_optional;
    typedef ::xsd::cxx::tree::traits< description_type, char > description_traits;

    const description_optional&
    description () const;

    description_optional&
    description ();

    void
    description (const description_type& x);

    void
    description (const description_optional& x);

    void
    description (::std::unique_ptr< description_type > p);

    // author
    //
    typedef ::IDS::author author_type;
    typedef ::xsd::cxx::tree::optional< author_type > author_optional;
    typedef ::xsd::cxx::tree::traits< author_type, char > author_traits;

    const author_optional&
    author () const;

    author_optional&
    author ();

    void
    author (const author_type& x);

    void
    author (const author_optional& x);

    void
    author (::std::unique_ptr< author_type > p);

    // date
    //
    typedef ::xml_schema::date date_type;
    typedef ::xsd::cxx::tree::optional< date_type > date_optional;
    typedef ::xsd::cxx::tree::traits< date_type, char > date_traits;

    const date_optional&
    date () const;

    date_optional&
    date ();

    void
    date (const date_type& x);

    void
    date (const date_optional& x);

    void
    date (::std::unique_ptr< date_type > p);

    // purpose
    //
    typedef ::xml_schema::string purpose_type;
    typedef ::xsd::cxx::tree::optional< purpose_type > purpose_optional;
    typedef ::xsd::cxx::tree::traits< purpose_type, char > purpose_traits;

    const purpose_optional&
    purpose () const;

    purpose_optional&
    purpose ();

    void
    purpose (const purpose_type& x);

    void
    purpose (const purpose_optional& x);

    void
    purpose (::std::unique_ptr< purpose_type > p);

    // milestone
    //
    typedef ::xml_schema::string milestone_type;
    typedef ::xsd::cxx::tree::optional< milestone_type > milestone_optional;
    typedef ::xsd::cxx::tree::traits< milestone_type, char > milestone_traits;

    const milestone_optional&
    milestone () const;

    milestone_optional&
    milestone ();

    void
    milestone (const milestone_type& x);

    void
    milestone (const milestone_optional& x);

    void
    milestone (::std::unique_ptr< milestone_type > p);

    // Constructors.
    //
    info (const title_type&);

    info (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0);

    info (const info& x,
          ::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0);

    virtual info*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    info&
    operator= (const info& x);

    virtual 
    ~info ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::flags);

    protected:
    ::xsd::cxx::tree::one< title_type > title_;
    copyright_optional copyright_;
    version_optional version_;
    description_optional description_;
    author_optional author_;
    date_optional date_;
    purpose_optional purpose_;
    milestone_optional milestone_;
  };

  class ifcVersion_item: public ::xml_schema::string
  {
    public:
    enum value
    {
      IFC2X3,
      IFC4,
      IFC4X3_ADD2
    };

    ifcVersion_item (value v);

    ifcVersion_item (const char* v);

    ifcVersion_item (const ::std::string& v);

    ifcVersion_item (const ::xml_schema::string& v);

    ifcVersion_item (const ::xercesc::DOMElement& e,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

    ifcVersion_item (const ::xercesc::DOMAttr& a,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

    ifcVersion_item (const ::std::string& s,
                     const ::xercesc::DOMElement* e,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

    ifcVersion_item (const ifcVersion_item& x,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

#ifdef XSD_CXX11
    ifcVersion_item&
    operator= (const ifcVersion_item&) = default;
#endif

    virtual ifcVersion_item*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

    ifcVersion_item&
    operator= (value v);

    virtual
    operator value () const
    {
      return _xsd_ifcVersion_item_convert ();
    }

    protected:
    value
    _xsd_ifcVersion_item_convert () const;

    public:
    static const char* const _xsd_ifcVersion_item_literals_[3];
    static const value _xsd_ifcVersion_item_indexes_[3];
  };

  class author: public ::xml_schema::string
  {
    public:
    // Constructors.
    //
    author ();

    author (const char*);

    author (const ::std::string&);

    author (const ::xml_schema::string&);

    author (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

    author (const ::xercesc::DOMAttr& a,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

    author (const ::std::string& s,
            const ::xercesc::DOMElement* e,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

    author (const author& x,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

    virtual author*
    _clone (::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0) const;

#ifdef XSD_CXX11
    author&
    operator= (const author&) = default;
#endif

    virtual 
    ~author ();
  };
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace IDS
{
  // Parse a URI or a local file.
  //

  ::std::unique_ptr< ::IDS::ids >
  ids_ (const ::std::string& uri,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (const ::std::string& uri,
        ::xml_schema::error_handler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (const ::std::string& uri,
        ::xercesc::DOMErrorHandler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  // Parse std::istream.
  //

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::std::istream& is,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::std::istream& is,
        ::xml_schema::error_handler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::std::istream& is,
        ::xercesc::DOMErrorHandler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::std::istream& is,
        const ::std::string& id,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::std::istream& is,
        const ::std::string& id,
        ::xml_schema::error_handler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::std::istream& is,
        const ::std::string& id,
        ::xercesc::DOMErrorHandler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  // Parse xercesc::InputSource.
  //

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::xercesc::InputSource& is,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::xercesc::InputSource& is,
        ::xml_schema::error_handler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::xercesc::InputSource& is,
        ::xercesc::DOMErrorHandler& eh,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  // Parse xercesc::DOMDocument.
  //

  ::std::unique_ptr< ::IDS::ids >
  ids_ (const ::xercesc::DOMDocument& d,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());

  ::std::unique_ptr< ::IDS::ids >
  ids_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
        ::xml_schema::flags f = 0,
        const ::xml_schema::properties& p = ::xml_schema::properties ());
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/framework/XMLFormatter.hpp>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

namespace IDS
{
  // Serialize to std::ostream.
  //

  void
  ids_ (::std::ostream& os,
        const ::IDS::ids& x, 
        const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
        const ::std::string& e = "UTF-8",
        ::xml_schema::flags f = 0);

  void
  ids_ (::std::ostream& os,
        const ::IDS::ids& x, 
        ::xml_schema::error_handler& eh,
        const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
        const ::std::string& e = "UTF-8",
        ::xml_schema::flags f = 0);

  void
  ids_ (::std::ostream& os,
        const ::IDS::ids& x, 
        ::xercesc::DOMErrorHandler& eh,
        const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
        const ::std::string& e = "UTF-8",
        ::xml_schema::flags f = 0);

  // Serialize to xercesc::XMLFormatTarget.
  //

  void
  ids_ (::xercesc::XMLFormatTarget& ft,
        const ::IDS::ids& x, 
        const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
        const ::std::string& e = "UTF-8",
        ::xml_schema::flags f = 0);

  void
  ids_ (::xercesc::XMLFormatTarget& ft,
        const ::IDS::ids& x, 
        ::xml_schema::error_handler& eh,
        const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
        const ::std::string& e = "UTF-8",
        ::xml_schema::flags f = 0);

  void
  ids_ (::xercesc::XMLFormatTarget& ft,
        const ::IDS::ids& x, 
        ::xercesc::DOMErrorHandler& eh,
        const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
        const ::std::string& e = "UTF-8",
        ::xml_schema::flags f = 0);

  // Serialize to an existing xercesc::DOMDocument.
  //

  void
  ids_ (::xercesc::DOMDocument& d,
        const ::IDS::ids& x,
        ::xml_schema::flags f = 0);

  // Serialize to a new xercesc::DOMDocument.
  //

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
  ids_ (const ::IDS::ids& x, 
        const ::xml_schema::namespace_infomap& m = ::xml_schema::namespace_infomap (),
        ::xml_schema::flags f = 0);

  void
  operator<< (::xercesc::DOMElement&, const entityType&);

  void
  operator<< (::xercesc::DOMElement&, const idsValue&);

  void
  operator<< (::xercesc::DOMElement&, const classificationType&);

  void
  operator<< (::xercesc::DOMElement&, const partOfType&);

  void
  operator<< (::xercesc::DOMElement&, const applicabilityType&);

  void
  operator<< (::xercesc::DOMElement&, const propertyType&);

  void
  operator<< (::xercesc::DOMElement&, const attributeType&);

  void
  operator<< (::xercesc::DOMElement&, const materialType&);

  void
  operator<< (::xercesc::DOMElement&, const requirementsType&);

  void
  operator<< (::xercesc::DOMElement&, const specificationType&);

  void
  operator<< (::xercesc::DOMElement&, const specificationsType&);

  void
  operator<< (::xercesc::DOMElement&, const relations&);

  void
  operator<< (::xercesc::DOMAttr&, const relations&);

  void
  operator<< (::xml_schema::list_stream&,
              const relations&);

  void
  operator<< (::xercesc::DOMElement&, const upperCaseName&);

  void
  operator<< (::xercesc::DOMAttr&, const upperCaseName&);

  void
  operator<< (::xml_schema::list_stream&,
              const upperCaseName&);

  void
  operator<< (::xercesc::DOMElement&, const simpleCardinality&);

  void
  operator<< (::xercesc::DOMAttr&, const simpleCardinality&);

  void
  operator<< (::xml_schema::list_stream&,
              const simpleCardinality&);

  void
  operator<< (::xercesc::DOMElement&, const conditionalCardinality&);

  void
  operator<< (::xercesc::DOMAttr&, const conditionalCardinality&);

  void
  operator<< (::xml_schema::list_stream&,
              const conditionalCardinality&);

  void
  operator<< (::xercesc::DOMElement&, const ids&);

  void
  operator<< (::xercesc::DOMElement&, const entity&);

  void
  operator<< (::xercesc::DOMElement&, const partOf&);

  void
  operator<< (::xercesc::DOMElement&, const classification&);

  void
  operator<< (::xercesc::DOMElement&, const attribute&);

  void
  operator<< (::xercesc::DOMElement&, const property&);

  void
  operator<< (::xercesc::DOMElement&, const material&);

  void
  operator<< (::xercesc::DOMElement&, const requirements&);

  void
  operator<< (::xercesc::DOMElement&, const ifcVersion&);

  void
  operator<< (::xercesc::DOMAttr&, const ifcVersion&);

  void
  operator<< (::xml_schema::list_stream&,
              const ifcVersion&);

  void
  operator<< (::xercesc::DOMElement&, const info&);

  void
  operator<< (::xercesc::DOMElement&, const ifcVersion_item&);

  void
  operator<< (::xercesc::DOMAttr&, const ifcVersion_item&);

  void
  operator<< (::xml_schema::list_stream&,
              const ifcVersion_item&);

  void
  operator<< (::xercesc::DOMElement&, const author&);

  void
  operator<< (::xercesc::DOMAttr&, const author&);

  void
  operator<< (::xml_schema::list_stream&,
              const author&);
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // SCHEMA_IDS_BINDING_HXX
